### PR TITLE
Finished tc 100 

### PR DESCRIPTION
**Pull request by SF001User**
- Added cool code her e
- cool code there 
- cool code everywhere

### CODE REVIEW

**Comment by umitolmez** [comment]
well done

**Review by asliyakamoli — COMMENTED** [review]
great

**Comment by pmammedov** [comment]
Please some commits

**Comment by zinaemilian** [comment]
well done

**Comment by ConstantinBravo** [comment]
Great Job

**Comment by pmammedov** [comment]
good work is done

**Pull request merged**
